CONTENTFUL_SPACE_ID     = "j2bkpry69ktm"
CONTENTFUL_ENVIRONMENT  = "master"
RESEND_FROM_EMAIL       = "no-reply@novotec-gruppe.de"
RESEND_TO_EMAIL_NONPROD = "info@novotec-gruppe.de"
RESEND_TO_EMAIL_PROD    = "info@novotec-gruppe.de"
URL_NONPROD             = "https://novotec-git-main-olgoetz.vercel.app"
URL_PROD                = "https://www.novotec-gruppe.de"
